<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'              #can only use return within a function

greeting("Super Man"), greeting(name="Super Man")

('Hello Super Man!', 'Hello Super Man!')

In [2]:
greeting('Batman')

'Hello Batman! So, nice to meet you!'

In [3]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [4]:
print(greeting(name='Super Man'))

Hello Super Man!


In [5]:
import numpy as np

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
basic_stats([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

(1, 10, 5.5)

In [6]:

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_min, list_max, list_mean)

1 5 3.0


### 1.2 Named functions that don’t return

In [7]:
#eg. print(). doesnt return a value 
#such functions often used to eg. save data to a file

### 1.3 Anonymous functions

In [8]:
my_short_function = lambda name: f"Hello {name}!"     #lambda function always returns the value of the last statement.
my_short_function(name="Super Man")

'Hello Super Man!'

In [9]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [10]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element
    

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [11]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [12]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting()

'Hello no one!'

In [13]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [14]:

# Your code here


### 2.2 A word of caution

In [15]:

# Your code here


## Exercise 1 :  Do you know why?

In [21]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting('hi')

'Hello hi!'

For any name that is not Batman, Python only registers the second return keyword since it "ignores" the if block which comprises of the first return keyword given that the name is not Batman?

## Exercise 2 :  Calculator functions

In [68]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 6, 56, 24, 73])

def add(x,y):
    return x+y                             #x and y alr are arrays, so no need surround the letters by square brackets
print(f"The sum of {x} + {y} is",add(x,y))

def subtract(x,y):
    return x-y
print(f"{x} subtract {y} is", subtract(x,y))


def multiply(x,y):
    return x*y
print(f"{x} multiplied by {y} is", multiply(x,y))

def divide(x1,y1):
    # Iterating through each element in y and returning error if any is 0
    if type(y1)==int:
        if y1==0:
            return "Division error!"
        else:
            return x1/y1
    else:
        for denominator in y1:
            if denominator == 0:
                return "Division error!"    #if there IS a zero, will return division error and "stop running", as in dont need to worry abt the code moving on to the following return bc can only return once. 
    
        return x1/y1                         #only after screening ALL elements in y for 0, then can divide array y by array x safely.
print(f"{x} divided by {y} is", divide(x,y))
    


The sum of [36 34 44 76 27] + [64  6 56 24 73] is [100  40 100 100 100]
[36 34 44 76 27] subtract [64  6 56 24 73] is [-28  28 -12  52 -46]
[36 34 44 76 27] multiplied by [64  6 56 24 73] is [2304  204 2464 1824 1971]
[36 34 44 76 27] divided by [64  6 56 24 73] is [0.5625     5.66666667 0.78571429 3.16666667 0.36986301]


In [44]:
np.array([5])

array([5])

In [69]:


divide(x,y)

array([0.5625    , 5.66666667, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [68]:
import numpy as np
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    numbers = np.array(numbers)
    return numbers.max(), numbers.argmax()

max_info([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

(83, 2)