<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [2]:
x = 10
assert x >= 0, "x is becoming negative!"

In [35]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [6]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.4
The square of 4 is 16!


In [8]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.lalalalala
Oh oh! I cannot square lalalalala!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [10]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

In [11]:
funny_add(1,2,3)

321

In [13]:
funny_add(c=3,b=1,a=2)

112

In [14]:
funny_add(b=1,a=2)

112

In [15]:
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

In [16]:
#funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

### 2.2 Docstrings

In [22]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how              
    positional, keyword and default arguments 
    work.
    '''
    #docstring needs to be sandwiched between a pair of ''' (or """) and can span multiple lines.
    return a + 10*b + 100*c
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how              
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [ ]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0 (ie. sin(pi/2))
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))   #x=pi/2 -> cos(pi)
#> -1.0

### 2.4 More unpacking

In [23]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [24]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [25]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [26]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [4]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

def add(x,y):
    return x+y                             #x and y alr are arrays, so no need surround the letters by square brackets
print(f"The sum of {x} + {y} is",add(x,y))

def subtract(x,y):
    return x-y
print(f"{x} subtract {y} is", subtract(x,y))


def multiply(x,y):
    return x*y
print(f"{x} multiplied by {y} is", multiply(x,y))

#def divide(x,y):
    #for denominator in y:
        #assert denominator !=0, "division error because a y element is zero!"    
    #return x/y                         #only after screening ALL elements in y for 0, then can divide array y by array x safely.
#print(f"{x} divided by {y} is", divide(x,y))

def divide(x,y):
    assert np.all(y!=0), "division error because a y element is zero"
    return x/y
print(divide(x,y))


The sum of [36 34 44 76 27] + [64  0 56 24 73] is [100  34 100 100 100]
[36 34 44 76 27] subtract [64  0 56 24 73] is [-28  34 -12  52 -46]
[36 34 44 76 27] multiplied by [64  0 56 24 73] is [2304    0 2464 1824 1971]


AssertionError: division error because a y element is zero

## Exercise 2 :  A better calculator II

In [43]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 0, 56, 24, 73])

def add(x,y):
    return x+y                             #x and y alr are arrays, so no need surround the letters by square brackets
print(f"The sum of {x} + {y} is",add(x,y))

def subtract(x,y):
    return x-y
print(f"{x} subtract {y} is", subtract(x,y))


def multiply(x,y):
    return x*y
print(f"{x} multiplied by {y} is", multiply(x,y))

def divide(x,y):
    np.seterr(all='raise')     #tells numpy to stop trying to continue dividing when there's an error
    try:
        return x/y
    except:
        print(f"I cannot divide {x} by {y}!")

print(f"{x} divided by {y} is", divide(x,y))




The sum of [36 34 44 76 27] + [64  0 56 24 73] is [100  34 100 100 100]
[36 34 44 76 27] subtract [64  0 56 24 73] is [-28  34 -12  52 -46]
[36 34 44 76 27] multiplied by [64  0 56 24 73] is [2304    0 2464 1824 1971]
I cannot divide [36 34 44 76 27] by [64  0 56 24 73]!
[36 34 44 76 27] divided by [64  0 56 24 73] is None
