<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [5]:
import numpy as np

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
#py = python lists

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
#np = numpy arrays

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
#dictionary. use of a key and an associated value separated by a : 

#for lists and arrays, order matters! and need 2 sets for this example

### 1.2 Accessing data from a list (or array)

In [9]:
print(py_real_names[1])
print(py_super_names[1])

print(py_real_names[-1])
print(py_real_names[2])

Tony Stark
Iron Man
Stephen Strange
Stephen Strange


### 1.3 Accessing data from a dictionary

In [16]:
print(superhero_info["Natasha Romanoff"])

# print(superhero_info["Black Widow"]) will not work. 

superhero_info.keys(), superhero_info.values()


Black Widow


(dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']),
 dict_values(['Black Widow', 'Iron Man', 'Doctor Strange']))

### 1.4 Higher dimensional lists

In [17]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

print(py_superhero_info[1])


['Tony Stark', 'Iron Man']


## 2 Lists vs. Arrays

### 2.1 Size

In [26]:

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

len(py_list_2d), len(np_array_2d), np_array_2d.shape


(10, 10, (10, 2))

### 2.2 Arrays are fussy about type

In [27]:
# NumPy arrays tolerate only a single data type while python lists can accommodate more than one data type
py_list = [1, 1.5, 'A']
np.array(py_list)
#numbers converted to english with ''
#KIV: can easily change type (typecast) using function astypes()

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
# py_list + 10 doesn't work

np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [35]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)


py_list_1 + py_list_2, np_array_1 + np_array_2
# adding Python lists together results in a new list containing all the original data
# adding Numpy arrays together results in a new list containing the original data added together based on their sequence in the lists. For this to work, the original lists must contain the same number of data!

([1, 2, 3, 4, 5, 10, 20, 30, 40, 50], array([11, 22, 33, 44, 55]))

### 2.5 Multiplying by a Number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2, np_array*2
#multiplying by a number makes a list repeat itself that number of times and grow, but multiplying by a number makes an array multiply its data elements by the number

([1, 2, 3, 4, 5, 1, 2, 3, 4, 5], array([ 2,  4,  6,  8, 10]))

### 2.6 Squaring

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#py_list**2 will not work
np_array**2, np_array**2 + 7
# array squares its data elements by the number

(array([ 1,  4,  9, 16, 25]), array([ 8, 11, 16, 23, 32]))

### 2.7 Asking questions

In [62]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)   

py_list == 3, py_list == [3], py_list == [1, 2, 3, 4, 5]
#this asks whether py_list is exactly the same as whatever is to the right of ==

# py_list > 3 will not work

np_array == 3
#this asks whether each data element in the array is 3

np_array > 3
#this asks whether each data element in the array is greater than 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [71]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list) #sum() is a base Python function, adds all data elements together

max(py_list) #max() is a base Python function, states largest data element in the list

min(py_list) #min() is a base Python function, states smallest data element in the list

#py_list.sum() wont work

np_array.sum()
np_array.mean() # gets the mean value of all data elements in the array
np_array.max()
np_array.min()

#Overall, generally speaking, an operation on a list works on the WHOLE list while that on an array works on the INDIVIDUAL elements of the array

1

## Exercise 1 :  Total recall?

2 similarities between lists and arrays:
1. lists and arrays serve to store data
2. both do not use a key and an associated value like dictionaries do (but can use a 2D list/array)

2 differences between lists and arrays:
1. an operation on a list works on the whole list but an operation on an array works on each individual data element of the array
2. arrays can only tolerate a single data type but lists can accommodate more than one data type.

A dictionary is also a way to store data, but uses a key and an associated value separated by a colon. In a sense, there is an input and output?

## Exercise 2 :  Index me

In [72]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [74]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
#if i am not wrong, the above lines make the associated values of each 'key' be in upper case?
superhero_info

{'Natasha Romanoff': 'BLACK WIDOW',
 'Tony Stark': 'IRON MAN',
 'Stephen Strange': 'DOCTOR STRANGE'}

## Exercise 4 :  How many ones

In [14]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_array = np.array(numbers)
np_array == 1   #this line is actually optional


(np_array == 1).sum()

#thus the number '1' appears 9 times

9